### PR TITLE
Close icon to Popover & typo fix

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**
Part of #1137

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
Hey @Dragomir-Ivanov, I think I remember discussing this, but I can't seem to find the issue. Can you link the issue here?

**Comment by Dragomir-Ivanov** [comment]
Hi @gabrielliwerant Editted the PR message above. This PR was discussed in part in #1137

**Comment by Dragomir-Ivanov** [comment]
I was thinking of this @gabrielliweran, unfortunately Popover already passes through `classes` prop down to `MuiPopover`. Trying to sneak another class for close button into this `classes` breaks things.
In short, I didn't found a way to do it. Any help appreciated.

**Comment by Dragomir-Ivanov** [comment]
Hi @gabrielliwerant I hope you are well.
Did some work in making close icon more customizable with a class.
Please review, and merge if okay. Thanks.

**Comment by Dragomir-Ivanov** [comment]
Ah, I wish I mentioned this couple of hours earlier. I am still using MUI v3(planning to move to v4, but not yet). Please merge to 2.15.0 if not much of a hassle. Also, will `mui-datatables` v3 will work with MUI v3? If not, consider releasing `mui-datatables` v4 to be in sync with MUI.

**Comment by patorjk** [comment]
@Dragomir-Ivanov Even though the focus is on getting it in-line with Material v4, it should be backward compatible with MUI v3 - in fact, there are only a few small things needed for Material v4.

I've released a beta of v3 which you can install here:

npm install mui-datatables@beta

Let me know if that works for you. If not, it's still possible for me to do another 2.x release with these changes (though I'd want to avoid that if possible).

The v3 release still isn't complete, as I want to incorporate a lot more of the outstanding PRs. The only current breaking change is the removal of fixedHeaderOptions (it's being replaced by fixedHeader and fixedSelectColumn options). There will be a few other small breaking changes, but I'll have everything written up when the release comes out.

**Comment by Dragomir-Ivanov** [comment]
Thanks @patorjk ! I will try that in next couple of days, and let you know if anything breaks.

**Pull request merged**
