### PR TITLE
Add Feature: onRowClick

### PR DESCRIPTION
**Pull request by Skn0tt**
mui-datatables is a great project! It helps me a lot at [EntE](https://gitlab.com/skn0tt/EntE).

There was one feature missing for me:

`onRowClick` gets called when a row is clicked.
It's provided the full `data` of that row.

### CODE REVIEW

**Comment by gregnb** [comment]
@Skn0tt Thanks for the feedback, man! Looks almost good to accept but can you make the following change:

I would like the callback parameters to look like this:

```
onRowClick(rowNumber, rowData)
```

**Comment by Codedrainer** [comment]
how can i use onRowsSelect ?

**Comment by gregnb** [comment]
@Skn0tt Can you make those changes?

**Comment by Skn0tt** [comment]
I'll return from my vacation in a week, then I'll get around to do this. Cheers :)

**Comment by Skn0tt** [comment]
Should be working now. I changed the signature to `(dataIndex: number, data: string[], rowIndex: number) => void`.

**Comment by gregnb** [comment]
Looks almost right can we match what I had above?
```
onRowClick(rowNumber, rowData)
```

make it so that the 2nd parameter is just an object that contains 
```
{ dataIndex: number, rowIndex: number} 
```

It will match what I have in another place

**Comment by Skn0tt** [comment]
What exactly should difference between `rowNumber` and `rowIndex` then be?
Wouldn't it be better to do:

```
onRowClick(rowNumber, { dataIndex: number, data: string[] })
```

**Comment by gregnb** [comment]
Ok, a mistake on my end. Can we change it to match the following? Sorry for the inconvenience.
I'm looking to probably update some of these other callbacks into the future to provide just an object that has the cell information (dataIndex and cellIndex/rowIndex)

```
onRowClick(rowData, rowMeta)
```

make it so that the 2nd parameter is just an object that contains 

```
{ dataIndex: number, rowIndex: number} 
```

What do you think?

**Comment by Skn0tt** [comment]
That seems better.
I'll implement it!

**Comment by gregnb** [comment]
Awesome, thanks man! Again, my bad!

**Comment by titulus** [comment]
Good job! This feature was last who blocks me from using this repo. :+1:

**Pull request merged**
