### PR TITLE
Add support for UTF-8 when downloading CSV

### PR DESCRIPTION
**Pull request by rinorbytyci**
This pull should add UTF-8 support for special / accented characters when downloading CSV files.

### CODE REVIEW

**Comment by patorjk** [comment]
This can also be done with the onDownload method:

```
onDownload: (buildHead, buildBody, columns, data) => {
    return "\uFEFF" + buildHead(columns) + buildBody(data); 
} 
```

The problem with always adding the BOM in is that it's Excel specific, and the actual character will show up in some spreadsheet programs (ex: https://github.com/react-csv/react-csv/issues/89).

**Comment by gabrielliwerant** [comment]
This library has intentionally steered away from providing specific types of exports as this can become a source of bloat. Specific implementations are left up to the devs and external libraries.

Perhaps a better use of this PR would be to add something to the documentation or to an example that points out how to work with downloads intended for Excel (or other programs).

**Comment by patorjk** [comment]
Excel specific, so closing for now. I'll add an example in the documentation though.

**Comment by jose1208** [comment]
// option
  downloadOptions: {
                filename: 'excel-format.csv',
                separator: ';',
                filterOptions: {
                    useDisplayedColumnsOnly: true,
                    useDisplayedRowsOnly: true,
                }
            },
//function         
 onDownload: (buildHead, buildBody, columns, data) => {
                component.pdfReportAutoTable(                              
                    columns,
                    data
                );
                return false;
            },

**Pull request closed without merging**
