### PR TITLE
Add React 18 Support

### PR DESCRIPTION
**Pull request by kvintanaka**
Upon upgrading MUI to the latest ([5.9.0](https://www.npmjs.com/package/@mui/material/v/5.9.0)) along with React 18, this issues up

Will add further details in the comment

### CODE REVIEW

**Comment by kartik-v** [comment]
Agree. Needed for all new development on React 18.

**Comment by pintosack** [comment]
This is needed very much. Looking forward to it.

**Review by mvandoff-avi — APPROVED** [review]

**Comment by grantweiss** [comment]
Any update on this?

**Comment by pintosack** [comment]
Is greg even around anymore?

**Comment by patorjk** [comment]
Is this literally all that's needed?

I'm a contributor on this project and could publish an update if need be. I'd prefer any PR be in its final form before I took a look at it though. It's been a long time since I've used this project, but I could help here if this is holding people up.

@pintosack[pintosack](https://github.com/pintosack) To my knowledge, no. He handed the project off a few years ago, then it got handed off to me (I was the 3rd maintainer), and then I later handed it off to someone else. These things are a lot of work and I just didn't have time to support it (plus I left the job where I was using it, so I had no incentive to work on it).

**Comment by patorjk** [comment]
@Usama-Tahir I don't think anyone is working on it. If you make the fix I can create a new version.

**Comment by Usama-Tahir** [comment]
@patorjk here is the PR with the fix. https://github.com/gregnb/mui-datatables/pull/1971

Please review it whenever you get some free time and if you need some changes in the PR, please let me know.

Thanks

**Pull request closed without merging**
