### PR TITLE
[WIP] #500 make filterType available at column level

### PR DESCRIPTION
**Pull request by guidouil**
A first step for the #500 
Please help make make this work 👍

### CODE REVIEW

**Comment by thalelinh** [comment]
Hi, how can I help you with this? I would very much enjoy this feature

**Comment by guidouil** [comment]
> Hi, how can I help you with this (besides the coverage)?

There is now 3 stuff to make this work

- [ ] make the filtering of datas work again
- [ ] correct the style
- [ ] update the tests

I'm currently working on the first one 😉

**Comment by guidouil** [comment]
Hello @gregnb (or anyone else),
Can you help me to make the code coverage raise again?
I've never used Mocha and I want this feature to exist.
Thank you

**Comment by guidouil** [comment]
Closing this PR because #527 is better 😄

**Pull request closed without merging**
