### PR TITLE
renderMultiselect filter type for null values

### PR DESCRIPTION
**Pull request by noobtiger**
Bug fix for renderMultiselect filter breaking for null values

### CODE REVIEW

**Comment by noobtiger** [comment]
@gabrielliwerant is the needs review label for me or someone else?

**Comment by noobtiger** [comment]
The issue is if there is a null value in the table and you select multiselect filter, the page is crashing

**Comment by gabrielliwerant** [comment]
@noobtiger I add the "Need review" label as a reminder/todo list for myself. If I intend to review, I also add myself to the "Reviewers" list in the PR details.

**Comment by noobtiger** [comment]
Awesome! Thank you very much.

**Pull request merged**
