### PR TITLE
Column options changing

### PR DESCRIPTION
**Pull request by VagnerNico**
Now you can control options outside the table, in the example added the filterOptions and filterList are changed outside the table.

### CODE REVIEW

**Comment by VagnerNico** [comment]
Coverage decreased because I inserted a new boolean condition here:
```javascript
if (this.state.columns.length && isEqual(this.rawColumns(newColumns), this.rawColumns(this.props.columns))  && !Object.keys(newColumns).some(val => this.state.columns[val] !== newColumns[val])) {
    const { columns, filterList, filterData } = this.state;
    return { columns, filterList, filterData };
}
```
I will try to write some test to raise up the coverage.

**Comment by VagnerNico** [comment]
tableChanging
Created a giant gif to show the example.

**Comment by VagnerNico** [comment]
By the urgency, I built locally and changed in my application, until now I didn't find any breaking with the other tables (not server-side).

**Comment by gabrielliwerant** [comment]
I believe this was fixed in `2.5.1`. Can you verify that is the case? If so, it still might good to have your example and test if you wouldn't mind paring this down to those changes only.

**Comment by VagnerNico** [comment]
Fixed in 2.5.1, works like a charm in my application.
I will update my local branch maintaining only the example and commit again.

**Comment by gabrielliwerant** [comment]
Continued here https://github.com/gregnb/mui-datatables/pull/848.

**Comment by gabrielliwerant** [comment]
Closed via https://github.com/gregnb/mui-datatables/pull/848.

**Pull request closed without merging**
