### PR TITLE
1826 remove @mui/styles from project

### PR DESCRIPTION
**Pull request by Fullbusters**
remove @mui/styles according to https://github.com/gregnb/mui-datatables/issues/1826

### CODE REVIEW

**Comment by Fullbusters** [comment]
@zxhmike @wdh2100 @ashfaqnisar @gregnb please take a look into this PR

**Comment by ashfaqnisar** [comment]
Hey @Fullbusters, Great Work Buddy.  I have connected this PR to my project and everything worked great. Didn't find any visible issues with the component. Will push the fixes if i found any later on.  Just had some lint issues, which I pushed a pr to you're repo.

**Comment by ashfaqnisar** [comment]
I think we have also have  update the readme, so the users should install tss-react along with the material ui packages

**Comment by Fullbusters** [comment]
@ashfaqnisar thanks, already update current pull request with your changes, thanks for fast review
please notify if I need do something fo merge it

**Comment by ashfaqnisar** [comment]
Hey @wdh2100, this looks great, can you go ahead merge this and we can push new changes if there are any issues in the future.

**Comment by liamlows** [comment]
Super excited to see this update, finally `@mui/styles` can go away haha

**Comment by wdh2100** [comment]
@Fullbusters 

thanks 😄 

It will have to be completely replaced later.
In my opinion, adding dependencies would be a burden later.

ref : https://mui.com/guides/migration-v4/#migrate-from-jss

**Comment by wdh2100** [comment]
I will release a new version soon

**Comment by Npervic** [comment]
@wdh2100 Hey was this released? still getting this when I migrated over to pnpm (from yarn) in v`^4.3.0`

**Pull request merged**
