### PR TITLE
Make selectToolbar an option: options.displaySelectToolbar = false

### PR DESCRIPTION
**Pull request by lamyfarai**

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
A request for something like this has come up numerous times (https://github.com/gregnb/mui-datatables/issues/783, https://github.com/gregnb/mui-datatables/issues/712, https://github.com/gregnb/mui-datatables/issues/451), but unfortunately, I haven't yet received an answer as to what would happen in this case if the user selects something and wants to take an action based on the selection?

I'd like to hear a good UX answer as to what a user should do without a select toolbar before I can consider adding a feature like this.

**Comment by lamyfarai** [comment]
@gabrielliwerant  What if you have, maybe 20 or 30 pages, and need to select items and not have an option to search  for "what to select". Such was my case anyways.

**Comment by gabrielliwerant** [comment]
@lamyfarai Keeping a search bar showing during the selection of rows I think is a valid use case, and I like that idea. However, I'd prefer to see an implementation that did just that: maintain the search bar during selection, rather than remove the select toolbar altogether.

Also, marking this is duplicate for now, because there has been a PR up already for this exact thing.

**Comment by patorjk** [comment]
I think this is a good idea. I needed to keep the search visible in one of my tables and wound up just implementing my own checkbox column to get around the select toolbar.

However, I'm not a fan of the implementation in https://github.com/gregnb/mui-datatables/pull/602 since you get 2 headers showing when you select an item (example here: https://codesandbox.io/s/mui-datatables-ehndq).

This PR also has the double toolbar issue (ex: https://codesandbox.io/s/github/lamyfarai/mui-datatables).

I think the optimal solution would be to have an option (say disableToolbarSelect) that if true, would keep the normal toolbar visible and not show the select toolbar if something was selected. Then as far as row selection goes, it'd be up to the developer to use the onRowsSelect callback to know what the selected items were.

I think all it would take is updating the PropTypes in MUIDataTable.js (line 134-ish) and modifying this line: https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L1184

    {selectedRows.data.length ? (

to be:

    {(selectedRows.data.length && this.options.disableToolbarSelect !== true) ? (

**Comment by manoj-raghuvanshi** [comment]
can someone merge this, I need this option.

**Comment by gabrielliwerant** [comment]
Version `2.13.0` has `disableToolbarSelect` which allows you to remove the select toolbar, which reveals the regular toolbar.

**Pull request closed without merging**
