### PR TITLE
refactor: upgrade `React` to `18` and `mui/*` to `latest`

### PR DESCRIPTION
**Pull request by Usama-Tahir**
This PR upgrades React to `18` and `mui/*` packages to the latest stable release.

### CODE REVIEW

**Comment by pintosack** [comment]
Looks good to me.

**Comment by Lori-Becker** [comment]
This is wonderful! I hope someone can merge this in and publish a new version ASAP!

**Comment by Lori-Becker** [comment]
@patorjk Can this be merged in? I know a lot of people are waiting for it.

**Comment by patorjk** [comment]
@Lori-Becker I'll take a look at this tonight.

**Comment by patorjk** [comment]
Thank you for putting this together. Just published it in the latest release.

**Comment by Xtabel** [comment]
This is awesome. Thank you for this. @Usama-Tahir  🙌

**Pull request merged**
