### PR TITLE
I've tested based on issue #275 the download CSV

### PR DESCRIPTION
**Pull request by diegochavez**
Using data instead of displayData? there's a specific functionality missing if we use data? we can prevent the React elements?

### CODE REVIEW

**Comment by Legogris** [comment]
With this change I am able to set `toString` on data objects and make the result show up in the generated CSV.

**Comment by gregnb** [comment]
Thanks for resolving this issue. Merged!

**Comment by darkhallow** [comment]
where is the file "MUIDataTableToolbar.js" location?

**Comment by mxdavis** [comment]
Still having this issue on nested objects. https://codesandbox.io/s/mutable-darkness-685n4?file=/src/index.js

**Pull request merged**
