### PR TITLE
Rendering of filters (#407) 

### PR DESCRIPTION
**Pull request by giupea**
Added customFilterListRender to column options (identity function as default)

### CODE REVIEW

**Comment by gregnb** [comment]
hey @giupea can you explain the use case for these changes? also provide an example. Someone has attempted this once in the past and I'm open to the change but this PR is light on details/README as well

**Comment by giupea** [comment]
Hi @gregnb, 
these changes provide the ability to define a custom label for the Chip component in TableFilterList.
As pointed out in #407, showing the filter value only can lead to ambiguous chips.
With these changes, one can add a 'customFilterListRender' property to column options to define what should be shown in column filterList chips.
I've just added to the PR changes to the README file and to column-filters example.

**Comment by gregnb** [comment]
Approved. Will merge into next release!

**Comment by bzemms** [comment]
Great but, why only render the chip? what about to render it under the filters popup ?

**Pull request merged**
