### PR TITLE
Allow for checking null and undefined.

### PR DESCRIPTION
**Pull request by jdetle**
Hi there, I think this was causing a bug for me when I was using the filter table functionality.

### CODE REVIEW

**Comment by gregnb** [comment]
@jdetle Thanks for the PR. Can you give me some detail as to what was going on?

**Comment by jdetle** [comment]
I cant give a minimum reproducible example but I had a basic table and was pressing the filter button but this gave an error where filterColumn was undefined, but still being referenced. I think this should prevent that from ever happening.

**Comment by aprakash-sovrn** [comment]
I believe this addresses https://github.com/gregnb/mui-datatables/issues/299, no?

**Comment by jdetle** [comment]
Yeah #299 looks right.

**Comment by jdetle** [comment]
🙏 thanks for the merge !

**Comment by aprakash-sovrn** [comment]
Did this go out in beta.55? Because I am still having this problem.

**Comment by chennanoka** [comment]
same here, updated to beta.55 still have the problem.

**Comment by gregnb** [comment]
it did go out but i've also received another PR with one more fix. try .56

**Pull request merged**
