### PR TITLE
[customFilterListRender] custom render also filter options in toolbar filter lists

### PR DESCRIPTION
**Pull request by bzemms**
#407

### CODE REVIEW

**Comment by bzemms** [comment]
@gregnb please review

**Comment by gabrielliwerant** [comment]
Hello, I'm trying to understand this use case a bit better. Can you provide a screenshot or example that demonstrates what you're going for in the UI?

**Comment by bzemms** [comment]
> Hello, I'm trying to understand this use case a bit better. Can you provide a screenshot or example that demonstrates what you're going for in the UI?

Sure, in case that you need to customize also the options in the filter popover... and not only the filter chip

image

**Comment by gabrielliwerant** [comment]
Thank you, will review when I get a chance.

**Comment by gabrielliwerant** [comment]
So, I think what you were looking for here is a way to have a custom rendering of the filters, is that correct?

If so, there is another implementation here which uses the new `filterOptions` API: https://github.com/gregnb/mui-datatables/pull/708. If that is what you need, then we should probably close this one. I'm sorry about that. Had we continued from here, I would have asked for an example and similar API additions as in the new PR, so it just happened to come up before I got around to reviewing this one.

**Comment by gabrielliwerant** [comment]
@bzemms Custom filter rendering is now available in `2.6.0` via `filterOptions: { display: Component }` and `filterType: 'custom'` in column options. I believe this satisfies the use case here, correct?

**Comment by bzemms** [comment]
> @bzemms Custom filter rendering is now available in `2.6.0` via `filterOptions: { display: Component }` and `filterType: 'custom'` in column options. I believe this satisfies the use case here, correct?

In fact its not the same thing, in my case I want to render each text of the checkbox filter , in #708 there is no filterData, and the custom render is only on static fields no matter what are the data in the table

**Comment by gabrielliwerant** [comment]
@bzemms You can do whatever you like inside the display option, including looping over all your data for a given column, and displaying checkboxes for each.

**Comment by gabrielliwerant** [comment]
Closing, as I believe everything here is now possible via filterOptions.

**Pull request closed without merging**
