### PR TITLE
Fix download filtered data only

### PR DESCRIPTION
**Pull request by jalamprea**
Based on [#440](https://github.com/gregnb/mui-datatables/pull/440) I have added support to the optional parameters to let users define when they want to export everything or only rows and columns filtered.

### CODE REVIEW

**Comment by jalamprea** [comment]
Hi @gabrielliwerant , do you know if this feature will be merged? or maybe do you want to suggest some other changes?

**Comment by andidev** [comment]
Does this really implement the ` filterOptions` suggestion from #440?
```
downloadOptions: {
  filename: 'tableDownload.csv',
  separator: ',',
  filterOptions: {
    useDisplayedColumnsOnly: true | false,
    useDisplayedRowsOnly: true | true
  } | false
}
```

**Comment by gabrielliwerant** [comment]
@jalamprea Will review soon!

**Comment by jalamprea** [comment]
yes, it's implementing that filters to allow devs to choose if the want to export all data or view only data.
Here are the propTypes: [src/MUIDataTable.js](https://github.com/gregnb/mui-datatables/pull/725/commits/a3ea286dfb3f45e8366b1782bbc8a1a4f3ee000c#diff-4f4aff53b74d2c551e37786d32b82e3a)
And here is the implementation [src/components/TableToolbar.js](https://github.com/gregnb/mui-datatables/pull/725/commits/a3ea286dfb3f45e8366b1782bbc8a1a4f3ee000c#diff-93991f6e37cbe8ff55a6d6b46b1d44f1)

**Comment by ali26Y** [comment]
can we get this merged plz :pray:

**Comment by ali26Y** [comment]
One potential problem is if a tables column uses `customBodyRender` this will export the column as `[object object]` if you could also fix this that would be awesome

**Comment by gabrielliwerant** [comment]
PR is continued here: https://github.com/gregnb/mui-datatables/pull/794.

@ali26Y, let me know if your problem is solved in the new PR.

**Comment by ali26Y** [comment]
Thank you @gabrielliwerant I will check it out and come back to you. Thank you for putting the time into this

**Comment by gabrielliwerant** [comment]
Options now available in `2.7.0`.

**Pull request closed without merging**
