### PR TITLE
Fix columns option display PropTypes

### PR DESCRIPTION
**Pull request by wdh2100**
- Add types boolean (true,false)

https://github.com/gregnb/mui-datatables/issues/1576

Name | Type | Default
-- | -- | --
display | `boolean or string`

### CODE REVIEW

**Comment by lounsbrough** [comment]
Can we get this PR merged? It would be great to eliminate errors from our app.

**Review by lounsbrough — APPROVED** [review]
LGTM

**Comment by wdh2100** [comment]
@lounsbrough 

thanks review,
I will be merging within this week.

**Comment by wdh2100** [comment]
@lounsbrough 

Fixed 3.7.2

**Comment by lounsbrough** [comment]
Awesome, thanks!

**Pull request merged**
