### PR TITLE
mui-datatables version 3.1.0

### PR DESCRIPTION
**Pull request by patorjk**
Branch for the 3.1.0 release of mui-datatables. It contains the following:

* Draggable Columns. (https://github.com/gregnb/mui-datatables/pull/1329)
* Added customBodyRenderLite. This is a more performant version of customBodyRender which doesn't affect filtering and takes in the dataIndex. (https://github.com/gregnb/mui-datatables/pull/1339/)
* Removed object deprecation notice for object data. Objects now officially supported. (https://github.com/gregnb/mui-datatables/pull/1339/)
* Added filterOptions.fullWidth. This setting allows filters to spread across the full width of the filter dialog. (https://github.com/gregnb/mui-datatables/pull/1340)
* Added onFilterChipClose. This is a callback that gets executed when a filter chip is closed. (https://github.com/gregnb/mui-datatables/pull/1341)

This list will grow.

The plan is to release this Sunday (June 21st).

### CODE REVIEW

**Comment by wdh2100** [comment]
#1338 

I will rewrite the pull request based on the branch

**Comment by wdh2100** [comment]
@patorjk 
any problem??

**Comment by patorjk** [comment]
> @patorjk
> any problem??

I had some test issues, I didn't realize some of them didn't work and got a little paranoid. I reverted two merges but realized the problem must have happened in the draggable columns branch (so I reverted the revert). I think I'm going to save the rest of your updates for next week's release. I meant to test these earlier but I've been pretty busy this weekend so I just didn't have time.

**Comment by wdh2100** [comment]
@patorjk 
Thanks!

it's not urgent that I added, so it's okay to slow down.

**Comment by mxmlnglt** [comment]
Hi @patorjk I saw you just released 3.1.0, that's great!
Also I noticed issues don't seem to be closed automatically e.g. the comment in #1340 didn't close the associated issue #1334.
Or another one #1040 you commented on but that is still open.

**Pull request merged**
