### PR TITLE
[WIP] Feature/migrate to mui v4

### PR DESCRIPTION
**Pull request by wuhuizuo**
## Changes
- Upgrade to material-ui v4 according to the [ v3 to v4 migrate Guide](https://material-ui.com/guides/migration-v3/)
- Fix grid spacing issue for migrating API changes.

## Testing

- all unit tests passed
- testing under latest `react` and `react-dom` passed.

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
Although I appreciate the effort here, this isn't quite the way I want to handle this. The PR is too large for me to properly review. What I'd like to do is collect any issues that migration causes into a bunch of separate PRs which can be reviewed and merged separately (as well as rolled back if there's an issue). If you'd still like to help with that, I'd be glad to have your help, just submit separate, small PRs for each migration issue and I'll be able to review each.

**Comment by wuhuizuo** [comment]
@gabrielliwerant ok, i will try by best.

**Comment by wuhuizuo** [comment]
@gabrielliwerant made commits pretty by rebase.

**Comment by patorjk** [comment]
Current migration effect for MUI v4 can be found here: https://github.com/gregnb/mui-datatables/pull/1300

I don't see anything additional from this PR for the upcoming version. However, if you notice something please feel from to jump in there.

**Pull request closed without merging**
