### PR TITLE
New onSearchOpen Callback

### PR DESCRIPTION
**Pull request by apercas**
This PR adds a new `onSearchOpen` callback triggered when the search box is displayed and also closes https://github.com/gregnb/mui-datatables/issues/210

Example of how to use this callback:
```
    const options = {
      filter: true,
      filterType: 'dropdown',
      responsive: 'stacked',
      onSearchOpen: ()=>{
       // your code here will be run after the user opens the search box
      },
    };

    return (
      <MUIDataTable title={"ACME Employee list"} data={data} columns={columns} options={options} />
    );
```

### CODE REVIEW

**Comment by gregnb** [comment]
@apercas I would like to see the onTableChange callback notified like we do in the other examples incase someone wants to use just that:

https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L514

You'll have to pass the setTableAction to the toolbar

**Comment by apercas** [comment]
OK, I'll take a look into it later on.

**Comment by apercas** [comment]
Hi, sorry for the delay on this, updated.

**Comment by gregnb** [comment]
Need the README updated

**Comment by apercas** [comment]
Sorry for the delay on this again, README updated.

**Comment by gregnb** [comment]
Thanks for the PR!

**Pull request merged**
