### PR TITLE
Radiobutton selection

### PR DESCRIPTION
**Pull request by hackedbellini**
* Allow to select items using a radio button 
* Reduce space wasted by radiobuttons/checkboxes in tables

### CODE REVIEW

**Comment by gregnb** [comment]
Thanks for the PR. I'll take some time tonight to review it

**Comment by hackedbellini** [comment]
@gregnb thanks!

**Comment by gregnb** [comment]
Hey @hackedbellini I appreciate the PR, but I'm not sure what enhancement this is going to bring? I ran this locally but again being a radio button it's only going to allow one choice at a time.  I don't see how that is an advantage of a checkbox which will allow you to check one or more. 

screen shot 2018-07-13 at 10 47 27 pm

I will have to unfortunately decline the PR

**Comment by hackedbellini** [comment]
Hi @gregnb 

I had to fork your lib in a product that I'm developing because, in a specific screen, I had to select one and only one item to display more info about it in a chart in the same screen. I cannot allow the user to select more than one row there.

The enhancement that it is going to bring is exactly that: Exclusive row selection when you need that.

If you don't see any advantage in having that in your lib, I guess I'll have to maintain my own fork of it, unfortunately :(

**Comment by hackedbellini** [comment]
Hi @gregnb ,

Sorry for being inconvenient, but just to be sure, even after my explanation from my previous comment this PR is not going to get merged?

I'm asking because I'm using this in more than one place in a project of my company and, if it won't get merged, I'll probably have to maintain and use my fork directly (which I started doing today).

**Comment by gregnb** [comment]
hey @hackedbellini I'm sorry to say but I will not merge the PR because it doesn't fit the vision I have for this package. The way I'm seeing it a user can select one checkbox or many so the checkbox is best suited for this library.

Sorry again, I truly appreciate the time you spent. I would encourage you to maintain the fork

**Pull request closed without merging**
