### PR TITLE
Changed fixed colors to mui palette colors

### PR DESCRIPTION
**Pull request by idobh2**
First of all - awesome component! thanks 👍 

This PR aims to introduce some dynamic color styling based on the material-ui palette object.
One good use case for it is using a dark mui palette, like partially mentioned in #272, which results in a "broken" table header, selection cells and label (sue to fixed color styling).

So with these changes, the following theme passed to a wrapping MuiThemeProvider actually renders a fully dark themed table

```
createMuiTheme({
  palette: {
    type: "dark",
  },
})
```

One thing I did leave is the checkboxes coloring, which by default uses the "secondary" color. The stated color (#027cb5) seemed too accurate, so i figured someone really wanted this color. I can change this too, to either secondary or primary if required. or it can stay this way and be set through style overrides. your call.

### CODE REVIEW

**Comment by idobh2** [comment]
Sure, sorry, should have done it to begin with:
### Before change - default view:
prechange-light
prechange2-light

### Before change - dark view:
prechange-dark
prechange2-dark

### After change - deafult view:
postchange-light
postchange2-light

### After change - dark view:
postchange-dark
postchange2-dark

**Comment by gregnb** [comment]
I'll test this out tonight

**Comment by tonymckendry** [comment]
What's the status on this PR? I'm attempting to use the component with a dark theme and running into the header styling issues. In the meantime is there a workaround I can use? I can't seem to get custom overrides to apply to those parts of the component.

**Comment by Dragomir-Ivanov** [comment]
I am also waiting for this merge. Thanks for all of the good work!

**Comment by tonymckendry** [comment]
@idobh2 - I know this was looking good recently but it looks like you've got conflicts again - eagerly awaiting these needed changes.

**Comment by gregnb** [comment]
This feature is now available from #348

**Comment by piyush97** [comment]
Any way I can change that gray color to any another dark mode color?

**Pull request closed without merging**
