### PR TITLE
padding: 0 for defaultPaginationStyles root

### PR DESCRIPTION
**Pull request by joshwaiam**
Bug fix for issue #1049.

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
Hey @joshwaiam, thanks so much for getting involved!

I'm trying to test the change, but I'm having trouble finding where the breakage occurs normally. On `master`, this is how the table looks in mobile mode in my dev tools:

image

**Comment by patorjk** [comment]
I also can't reproduce this. I went to https://www.material-ui-datatables.com/ on my phone and then clicked one of the examples in the sidebar (which pops a codesanbox example) and it seems to be displaying correctly.

**Comment by joshwaiam** [comment]
I'm sorry for wasting everyone's time on this.  I tried it in a new project and it does appear to be working fine without this fix.

**Comment by patorjk** [comment]
No worries! I’m a heavy user of this table so I appreciate people looking into things like this.

**Comment by joshwaiam** [comment]
I think I've been able to figure out when this happens, but not sure it's something readily fixable.  When trying to use the MUIDataTable inside of MUI's Container or a Grid, the padding of those parent containers causes the footer row to shift.  Looking through the mui-datatables docs to see if there is something I'm missing to address this, as using the datatable within a layout seems a common use-case!

**Pull request closed without merging**
