### PR TITLE
feat: Removed tss-react and replaced it with the default "styled" styling of mui.

### PR DESCRIPTION
**Pull request by ashfaqnisar**
Replaced all of the components with the `styled` styling in mui.
Updated the examples with the new `styled` styling.
Removed tss-react from deps.

For this issue https://github.com/gregnb/mui-datatables/issues/1826

### CODE REVIEW

**Comment by ashfaqnisar** [comment]
Hey @wdh2100 buddy, please let me know if there are any changes or issues with the PR. Would be happy to resolve them. I have connected the repo to my project and everything worked great.

**Comment by ashfaqnisar** [comment]
I have connected the repo to my project and everything worked great. If anyone can connect this PR to their project and check whether there are any issues with the PR,  that would be great.

**Comment by garronej** [comment]
Hi,  
I am obviously biased  on this issue but why did you go through the trouble of removing `tss-react`.  
I assume that it is the fact that it's an extra peer dependency?

**Comment by ashfaqnisar** [comment]
Closing this PR. As tss-react seems to better option than the styled for readability and understanding as we update the project.

**Comment by garronej** [comment]
Hi @d0lb33,  

It's not your fault, the documentation isn't up to date.  [See answer](https://github.com/gregnb/mui-datatables/pull/1882#issuecomment-1068607552).  
A custom emotion cache need to be provided for `mui-datatables` to work properly.   

```typescript
import { render } from "react-dom";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";

export const muiCache = createCache({
    "key": "Mui",
    "prepend": true
});

//NOTE: Don't use <StyledEngineProvider injectFirst/>
render(
    <CacheProvider value={muiCache}>
        {/* ...their app...*/}
    </CacheProvider>,
    document.getElementById("root")
);
```  

Tag me if you need further assistance.   

Best regards

**Comment by hornandrewm** [comment]
@garronej can you provide a codesandbox or equivalent of both `@mui` and `mui-datatables` being the latest version with custom css working on the mui datatable classes? I could only get them to work on mui-datatables v4 and not the latest version.

**Comment by garronej** [comment]
@hornandrewm sure

**Comment by garronej** [comment]
@hornandrewm I'll admit that I have some trouble making it work but I am not a familiar with `mui-datatable`. I am just here to provide support relative to the styling engine they use.  
This is what I have acheived: https://codesandbox.io/s/cool-thunder-j6cwmj?file=/src/App.js  

Basically if you have problem with style only applying when you add `!important` or SSR rendering you can ping me, it's my realm. For the rest it's on the core team.  

Best regards

**Comment by hornandrewm** [comment]
> @hornandrewm I'll admit that I have some trouble making it work but I am not a familiar with `mui-datatable`. I am just here to provide support relative to the styling engine they use. This is what I have acheived: https://codesandbox.io/s/cool-thunder-j6cwmj?file=/src/App.js
> 
> Basically if you have problem with style only applying when you add `!important` or SSR rendering you can ping me, it's my realm. For the rest it's on the core team.
> 
> Best regards

Unfortunately the docs on this repo say that you can use mui's global overrides/themes to style it's components. The example you provided is just using a class to style something conditionally and not a global theme. The codesandbox I gave you above works for v4 (before tss-react) and now fails and and I'm assuming it's because mui/tss-react don't share a global theme or something similar. Either way, it's very unfortunate that this functionality was broken after swapping to tss-react.

**Comment by garronej** [comment]
Ok I'll have annoter look

**Comment by garronej** [comment]
@hornandrewm, @d0lb33 Ok, I got it. The `styleOverrides` it's an easy fix I will submit a PR.  
Please don't hate TSS for it, this it's not the problem it's the solution, removing it and merging this PR doesn't fix the bug.  
And don't hate this lib's maintainer either. The migration from material-ui v4 to MUIv5 is very challenging.

**Comment by garronej** [comment]
@d0lb33 @hornandrewm Sorry for my previous messages, they where misleading. It's fixed in the PR #1882.  
Now It just needs to get merged....  
It's was not a bug in `tss-react` though... it was just a feature that this library's maintainer assumed to be present but wasn't 🙂  
[It's no longer the case](https://docs.tss-react.dev/mui-theme-styleoverrides)

**Pull request closed without merging**
