### PR TITLE
Add options to CSV download

### PR DESCRIPTION
**Pull request by tyrsensei**
This PR adds the ability to customize the download option with:
* filename changing
* separator changing
* hide columns in download file

### CODE REVIEW

**Comment by gregnb** [comment]
Hey @tyrsensei thanks for the PR. Allow me some time to think about adding this feature in. I'm not sure I'm 100% for everything being offered so far but I'll review some more in the coming week

**Comment by DanielGarciaGuillen** [comment]
Would love to see this feature!

**Comment by tyrsensei** [comment]
Hi @gregnb.

No problem for me. I implemented these features because I was asked to for un professional project. I thought it would be a better idea to make these available to the community.

I tried to stick at the way things were developped, but I might have failed, so feel free to tell me if some things need corrections.

**Comment by gregnb** [comment]
@tyrsensei It looks good to me. I just needed some time to look at it. Can you fix the merge conflicts? I'll approve it after

**Comment by tyrsensei** [comment]
@gregnb Conflicts resolved, feel free to come back to me if needed.

**Comment by gregnb** [comment]
Looks good! Thanks for the PR!

**Comment by ouchaaou** [comment]
@gregnb 
I ask if we can export in CSV only filtred data ?

**Pull request merged**
