### PR TITLE
Made all functionality work with components, updated example to show

### PR DESCRIPTION
**Pull request by tgBryanBailes**
Made it so that DOMServer renders a component, then uses textContent to strip out all of the text for search, filter, and CSVExport. Updated example to demonstrate using a component for inline editing, adhering to Material guidelines.

### CODE REVIEW

**Comment by gregnb** [comment]
Hey Bryan, thanks for opening this PR. I'm on vacation currently but I'm skimming through your commits so I'll try to get to this when I get some free time. I've never used DOMServer in the client so I'm wondering what your experience has been?

I know it's allowed in browser but I'm looking out on the web for people's experiences and not finding much. I think it's a good solve and I thought about it myself as a way to get the pure text of any component but felt like ok this should only be on the server side, you know?

**Comment by tgBryanBailes** [comment]
HI gregnb, I did all testing within the browser and all seemed to work fine as long as you stick to `renderToString()` and `renderToStaticMarkup()`

**Comment by gregnb** [comment]
hey @jungrafael I know you did some work on #4 to extract text out of components.  What do you think of this here? I'm going to test this when I get some free time over the next week but this could be a better solve?

**Comment by gregnb** [comment]
@tgBryanBailes Took a little bit of time to start going through this and I've found a couple of things that are a little concerning. 

-------------------

I've tried playing around with the text extraction and to me there's a noticeable lag every time I hit a key in the search box using the demo example.  This data set is small so each key should respond quickly: 

**Steps to recreate:**
1) Load your example
2) Click search
3) Monitor performance and enter word "business analyst"

**ReactDOMServer version:**
screen shot 2018-03-13 at 12 53 08 pm

**Current version without ReactDOMServer:**
screen shot 2018-03-13 at 12 52 01 pm


This issue needs to be investigated some more

-------------------

Also, the results returned when searching for "Business Analyst" do not seem correct:
screen shot 2018-03-13 at 12 42 39 pm
 
-------------------

Typography component is gone from the title in the toolbar:

**Actual:**
screen shot 2018-03-13 at 12 22 48 pm

**Expected:**

screen shot 2018-03-13 at 12 25 55 pm

While it's a minor issue I believe we need a separation of concerns for addressing the two issues: text extraction when components are provided for cells and unused vars/cleanup work. Some of the unused vars you found were good but it would be better to review this as **two separate PR's**.

**Comment by tgBryanBailes** [comment]
Hi gregnb, I believe that the missing Typography component was a result of bumping the version of Material-UI to the latest beta, not removing unused vars. I also have some ideas for improving the performance of the text parsing. As for the search results, I do not currently have the select component updating the underlying data set, so if values are changed they will not appear correctly in the search results. I assumed that any changes to underlying data would happen in a data store such as Redux in the real world, so did not implement it in the example. I will work through these issues today, so expect a commit.

**Comment by gregnb** [comment]
@tgBryanBailes Ah, ok my mistake then. I'll be in between flights today but when I get some downtime I'll pull down the latest changes and test them

**Comment by jungrafael** [comment]
Hi, this seems to be an interesting approach, since it allows to search the text inside rendered components as well. I'll take a better look at it, but my only concern is only with performance.

**Comment by gregnb** [comment]
@jungrafael Same but @tgBryanBailes has made some updates. I'm going to test some more to see the performance increase but this could be a solution to your ticket as well

**Comment by gregnb** [comment]
hey @tgBryanBailes so I pushed some changes into your branch.  Your changes worked nicely addressed the issues when searching but I found another performance issue. When the data set gets increased to something larger (in my example, 1800 rows) it takes a noticeable amount of time to load. A lot of time gets spent in getText()

Try running what I pushed up and maybe even increasing the data set even more to 5000.  Then try and change getText to not use DOMServer to see the difference in speed.  Not sure how we could address this problem. If you can find a way, I think we're really close to merging this

**Comment by tgBryanBailes** [comment]
You can go ahead and close this out. I am going to take your latest version and have a new idea for implementing this functionality. Expect a commit from me later today.

**Comment by gregnb** [comment]
Ok @tgBryanBailes sounds good!

**Pull request closed without merging**
