### PR TITLE
Add jsonMode option

### PR DESCRIPTION
**Pull request by mgolkardev**
Add jsonMode option for support array of object data

### CODE REVIEW

**Comment by gregnb** [comment]
So people have been asking about accepting array of objects for a long time now. I will be willing to accept this PR with some changes:

1) I don't want an explicit option so can we just detect if a user is passing in an array of arrays (current implementation) and if they are not then handle the array of objects
2) Change 'field' to 'id' and document this in the README. Specify how `name` is the label and `id` is the true column id
3) Something in the README to show that it accepts both array of arrays and array of objects

**Comment by abrhim** [comment]
I could really use the JSON mode in my project and I am willing to finish this up. @mgolkardev, I saw that you worked on it Jan. 5th. What remaining work is there?

**Comment by apercas** [comment]
If @abrhim couldn't work on this I'll be glad to help and move this forward.

**Comment by JRamos1993** [comment]
This PR as it is will prevent other functionalities like Sorting/CustomBodyRender, etc from working correctly.

**Comment by gregnb** [comment]
The latest release now supports data as objects. Example: https://github.com/gregnb/mui-datatables/blob/master/examples/data-as-objects/index.js

**Pull request closed without merging**
