### PR TITLE
add server side support + move activeColumn to root - WIP

### PR DESCRIPTION
**Pull request by gregnb**
When merged, this should resolve:
#141 
#153 
#152
#119
#148

TODO:
- more testing
- README

**How to use:**

Provide the following options: 

```
 serverSide: true,
 onServerRequest: (action, tableState) => {
   // a developer can respond to changes on an action basis
   // or take the state of the table as a whole decide the best course of action
 }
```

### CODE REVIEW

**Comment by gregnb** [comment]
@rooby Here's the PR I was mentioning. Would love some help in testing. I believe it's close

**Comment by titulus** [comment]
@gregnb it's only about pagination? what about whole stateless-mode?

**Comment by gregnb** [comment]
@titulus the example is only about pagination but that serverSide mode puts the responsbility of 

- pagination
- sorting
- filtering

on the user to handle from their remote source

**Comment by allenjoy123** [comment]
I'm using this component in my app and perform all the operations on large quantities of data. So I resorted to fetching data from the api service in pages. I am waiting for the serverside feature to be ready. can I still use the untested code before it is released.

**Comment by gregnb** [comment]
@allenjoy123 I can't stop you of course but I would wait. I'm going to try to wrap this up in the next day or two max

**Comment by gregnb** [comment]
I'm going to approve this PR and do a release. Lots of people have asked for this feature and we'll deal with bugs as they come

**Comment by allenjoy123** [comment]
Thank you for your efforts

**Comment by mehmetboraezer** [comment]
> @titulus the example is only about pagination but that serverSide mode puts the responsibility of
> 
> * pagination
> * sorting
> * filtering
> 
> on the user to handle from their remote source

Hi @gregnb, could you add sorting and filtering example?

**Comment by ronaiza-cardoso** [comment]
@mehmetboraezer could you reproduce the filtering example?

**Pull request merged**
