### PR TITLE
Fix for 868 (selectableRowsHeader option)

### PR DESCRIPTION
**Pull request by patorjk**
https://github.com/gregnb/mui-datatables/issues/868

* Added the option selectableRowsHeader that allows you to show/hide the header checkbox for selectable rows.

Quick view: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/hide-header-checkbox

### CODE REVIEW

**Comment by patorjk** [comment]
Poking around a bit, I noticed this PR is actually very similar to this PR https://github.com/gregnb/mui-datatables/pull/384, though that one is out of date and has a slightly different implementation. If this PR is accepted, it'd be able to close that one too.

**Comment by gabrielliwerant** [comment]
Looks like this might also address an old PR https://github.com/gregnb/mui-datatables/pull/384.

**Comment by eminence88th** [comment]
Hi @patorjk @gabrielliwerant , how can I hide the checkbox in the header but still show in the rows of data. I just don't want it to be in the header. How can I do that?

**Comment by patorjk** [comment]
@eminence88th see the selectableRowsHeader option.

**Pull request merged**
