### PR TITLE
Pass full row rather than single value to getTableMeta rowData parameter when rendering rows

### PR DESCRIPTION
**Pull request by xantorres**

### CODE REVIEW

**Comment by Badji** [comment]
Any news on this PR @gregnb ?

**Comment by nathancharles** [comment]
Is there any update on this PR?

**Comment by SergeyShiryaev** [comment]
The problem is important, actually. I have a lot of crutches to get around the problem of returning one value. This fix should fix the problem.

**Comment by gabrielliwerant** [comment]
Can someone explain what was broken before that this PR fixes with a specific example?

**Comment by patorjk** [comment]
After investigating this, this does appear to be fixed. Closing.

**Pull request closed without merging**
