### PR TITLE
#157 add Menu drawer on documentation website

### PR DESCRIPTION
**Pull request by benjaminbours**
#157 First version with fake links. I'm waiting for feedback about the best way to create the sandboxes.

### CODE REVIEW

**Comment by gregnb** [comment]
Ok, this is great work man. Thank you. Let me look at some other doc example sites and figure out how to proceed with this. We'll keep this PR up as WIP

**Comment by gregnb** [comment]
Some Examples you can fill in for now:

Custom Component: https://codesandbox.io/s/xrvrzryjvp
Customize Columns: https://codesandbox.io/s/xowj5oj8w
Custom Footer: https://codesandbox.io/s/5z0w0w9jyk
Customize Styling: https://codesandbox.io/s/0ylq1lqwp0
Custom Toolbar: https://codesandbox.io/s/wy2rl1nyzl
Custom ToolbarSelect: https://codesandbox.io/s/545ym5ov6p
Resizable Columns: https://codesandbox.io/s/q8w3230qpj

I think we should make them embed views what do you think? https://codesandbox.io/embed/q8w3230qpj?autoresize=1&hidenavigation=1

**Comment by benjaminbours** [comment]
Yes It's a nice presentation, good idea 👍

**Comment by gregnb** [comment]
Soon as the conflicts are resolved I'll look to merge this. Thanks for help again!

**Comment by benjaminbours** [comment]
My god, I realy sucked with the package-lock.json, I will never remove it again from a repo ! :p

**Comment by gregnb** [comment]
No worries. Thanks!

**Pull request merged**
