### PR TITLE
enableNestedDataAccess option to disable nested data when needed #909

### PR DESCRIPTION
**Pull request by domind**
also added 2 tests for  option `enableNestedDataAccess : false` :
1. making sure that table is not generated same way like when with  `enableNestedDataAccess : true` 
2. table is correctly omitting nested data.

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
Hello @domind. Can you explain the use case for shutting off this functionality via an option? It was my thinking that one would simply not use the dot notation if he/she did not want to use nested data.

**Comment by domind** [comment]
Hi @gabrielliwerant you [proposed to add this as an option](https://github.com/gregnb/mui-datatables/issues/909#issuecomment-530145855)  

> I'm open to suggestions about how to work around this. It's a little messy, but we could add an option like enableNestedDataAccess which could be flagged on or off to enabled/disable parsing the dot.

Right now, by default nested data are enabled, so if there is a dot in name data are not displayed.

**Comment by gabrielliwerant** [comment]
@domind Ok, thanks for reminding me. So, another way to do this would be to allow an option for choosing which character to use as a separator for objects. The advantage of this approach would be that there would be a way for someone to use this feature even if there are dots in the names, instead of having to choose between enabling/disabling the feature, What do you think?

**Comment by domind** [comment]
Sounds reasonable. Should we still keep name "enableNestedDataAccess" in such case? Guess default will be enabled with dot as separator, but should we allow to disable it completely? 
Might be to rename it to nestedDataSeparator and it would take string value, and "disable" string would turn it off. Should I rewrite it that way?

**Comment by domind** [comment]
@gabrielliwerant - arranged following:
- changed enableNestedDataAccess to string, so now nested data can use any separator,
- default value in case option is omitted is set to `'.'` (processing of nested data enabled)
- to disable - you need to pass empty string `enableNestedDataAccess : ''`

**Comment by patorjk** [comment]
Thank you for putting this together!

I've gone ahead and merged this into v3 and added some documentation in the README.

This feature was previously mentioned only in one example, and that was for something else and wasn't even linked on the README page. So it was kind of a hidden feature. I actually think having it on by default is bad since it leads to confusing bugs as seen in https://github.com/gregnb/mui-datatables/issues/909. I think I'm going to set it to be off by default in v3. It's a breaking change, but I'll have it documented in the write-up for v2 to v3.

**Pull request merged**
