### PR TITLE
Added sortOrder option (deprecating sortDirection on columns object)

### PR DESCRIPTION
**Pull request by patorjk**
In the current API, the table's sort direction is held in one of the column options objects. This has the following problems:

* It leads to ambiguity if multiple columns have this field set.
* It's makes it hard to implement multiple level sorting (where a table is first sorted by 1 column, and then for values that are the same a second column is used to sort). You can see an example of this in [jQuery Datatables](https://datatables.net/) - click a column header, and then shift+click another header. The second column is used to break ties.
* It adds unnecessary complexity to users who use the serverSide option, since a sort value is typically passed to the server separately, and in the current implementation it burred in one of the column's options.

This PR removes sortDirection from the column's object, and creates a "sortOrder" property on the options, examplet:

    var options = {
        sortDirection: {
            name: ${selectedColumn},
            direction: ${direction}
        }
    };

<del>I may change columnName to "name" and sortDirection to "direction". </del>

### CODE REVIEW

**Comment by wdh2100** [comment]
serverSide should change the option, right?

>I may change columnName to "name" and sortDirection to "direction".

me, too

```js
var options = {
    sortDirection: {
        name: ${selectedColumn},
        direction: ${direction}
    }
};
```

**Comment by patorjk** [comment]
@wdh2100 I think you're right, backward compatibility for something like this is a good idea. I've updated the PR to account for "sortDirection" if no sortOrder value is present. I also updated the field names.

**Comment by mxmlnglt** [comment]
@patorjk you said earlier "It's makes it hard to implement multiple level sorting": can you confirm this is not yet implemented?

**Comment by patorjk** [comment]
Correct, it's not yet implemented.

**Comment by broncha** [comment]
Didn't this disable sort by multiple columns? Now you can only sort by one column

**Pull request merged**
