### PR TITLE
Missing data for custom action columns

### PR DESCRIPTION
**Pull request by gabrielliwerant**
Addresses https://github.com/gregnb/mui-datatables/issues/443.

There were two issues.

1. Missing fields in data were causing errors
1. Data arrays of arrays did not properly render `customBodyRender` when data was missing

Added an example under `custom-action-columns`. Not sure what the best name for this kind of use case would be, so I'm open to suggestions.

Let me know what you think.

UPDATED:

~~Added an API option for columns called `hasData` which defaults to `true`. When `false`, it signifies that a column should be skipped when checking for data. This is only relevant for the array of arrays data structure, but allows full use of empty columns or `customBodyRender` in those cases.~~

~~Not sure that the API option is super obvious, but I couldn't think of another way to distinguish data in the array of arrays structure as intentionally absent.~~

Added an API option for columns called `empty` which defaults to `false`. When `true`, it signifies that a column should be skipped when checking for data. This is only relevant for the array of arrays data structure, but allows full use of empty columns or `customBodyRender` in those cases.

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
Just noticed an edge case here where no-data columns other than the last row cause the indexing to get messed up when transformed. Working on it and will push fixes here.

**Comment by gregnb** [comment]
What if we named it `empty` instead? and make the README something like `This denotes with the column has data or not` ?

**Comment by gabrielliwerant** [comment]
Updated with the API change.

**Comment by gregnb** [comment]
Ok great! I'll review this if I can get some free time tonight. Thanks again

**Comment by gregnb** [comment]
@gabrielliwerant Approved. I will merge this when I do the next release in the next couple of days

**Pull request merged**
