### PR TITLE
#977 Maintain filter state in buildColumns updates

### PR DESCRIPTION
**Pull request by acberk**
Addresses Issue https://github.com/gregnb/mui-datatables/issues/977

### CODE REVIEW

**Comment by gabrielliwerant** [comment]
Hey @acberk, thanks for looking into this. Just so I'm clear on what's being fixed while I'm testing, is it true that the filters are reset when filter state in the column options is manually updated? Or is there another cause?

**Comment by acberk** [comment]
@gabrielliwerant I'm not sure that's quite it. 

The contrived example showed the filters resetting when _any_ state was manually updated in the column options (in this case, the _onRowsSelect_ function).
https://codesandbox.io/s/muidatatables-example-u6u8b

From testing, that state update triggers _componentDidUpdate_ --> _setTableData_ --> _buildColumns_

The stack trace:

1. https://github.com/gregnb/mui-datatables/blob/ce277b48104de80120d64cecfa9d931282b6f483/src/MUIDataTable.js#L247
2. https://github.com/gregnb/mui-datatables/blob/ce277b48104de80120d64cecfa9d931282b6f483/src/MUIDataTable.js#L482
3. https://github.com/gregnb/mui-datatables/blob/ce277b48104de80120d64cecfa9d931282b6f483/src/MUIDataTable.js#L391

---

The filters are reset by any manual state call within the column options. It appears that the component updates when state is called. Is that intended? My fix passes the filter data through the _buildColumns_ function so that any previous filters remain active on component updates.

**Comment by patorjk** [comment]
@acberk in the way the table currently works, all state is erased when the table re-renders - filters, sorting, search text, selected rows, etc etc (see this issue: https://github.com/gregnb/mui-datatables/issues/807). I've put in another PR that will cause state to persist during re-render if it's not being overwritten by inputted options or column data. You can see it here if you're interested: https://github.com/gregnb/mui-datatables/pull/1086

**Comment by acberk** [comment]
@gabrielliwerant Did you have a chance to look at this? I've seen a lot of talk around derived state, but this smaller PR should take care of cases where selecting a row incorrectly resets the filters.

In other news, I found that I can work around it by self-managing filter state, and passing it down to each column with the filterList option. But this feels like a workaround.

**Comment by patorjk** [comment]
@acberk Using the filterList option is how you're currently supposed to preserve state with filters (see @gabrielliwerant's comment here: https://github.com/gregnb/mui-datatables/issues/807#issuecomment-517817791). An in-depth discussion of the problem can be found in https://github.com/gregnb/mui-datatables/issues/807.

This PR seems to only address the filterList option, and it doesn't allow the user to override the filterList from the option's object once the table has created a filterList (which prevents developers from loading filters externally after the table is loaded). There is another PR https://github.com/gregnb/mui-datatables/pull/1086 that would make all options, including filterList, persist on rerender if not overwritten on the options object.

**Comment by acberk** [comment]
@patorjk Fair enough, that makes sense. I don't think I knew about the filterList option during this fix. Sounds like that'll be the answer in the meantime. Thanks for chiming in.

**Pull request closed without merging**
