### PR TITLE
Feature/update mui icons

### PR DESCRIPTION
**Pull request by baer**
As of Material-UI beta-41, the material-ui-icons package was moved under the namespace `@material-ui`. See the [beta-41](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.41
) release notes for details. 

This PR updates the `material-ui-icons` package to the new `@material-ui/icons` and updates all code references to the name package name.

Note: This was a breaking change for `material-ui` and will therefore be a breaking change for `mui-datatables`. Not sure of the best way to handle this.

### CODE REVIEW

**Comment by gregnb** [comment]
Thanks for the PR @baer this should close #45

**Comment by gregnb** [comment]
@baer To your point, it's putting this package in a weird spot here. A breaking change based on a dependency should the semver go up a whole major? seems excessive. What are your thoughts?

**Comment by baer** [comment]
Humm, well for this project I see 3 problems:

*The Semver numbers depend on non semver projects*
`mui-datatables` relies on material-ui beta which may or may not have breaking changes between versions. Depending on the 1.x line was a calculated risk and I think was the right choice but it puts you in awkward situations when there are breaking changes like this one.

*_Real_ Semver vs. _Semver_ in the wild*
Semver is meant only as a system for alerting users to major/minor/patch changes but a lot of projects use it to mean both that _and_ to indicate changes in philosophy or major rebuilds/ refactors. To me, if you're going to say that a project uses semver, then use semver and don't be afraid of major revs. I feel strongly about this in projects I'm involved with but I respect that a lot of people do it differently.

*Semver for UI*
So that's by-the-book semver but `mui-datatables` has another issue and that's that semver doesn't really apply to UI. In my experience, I think that semver for apps just doesn't work but for libs like this you can treat the UI as a black box and do semver based on the integration points. If you start assuming that people are going to rely on specific pieces of DOM then you'll end up with a major on almost every release.

All this is to say that I think that major is just fine in this case :). Also, thanks for all the great work!

**Comment by gregnb** [comment]
@baer Thanks for the valuable feedback! Really great stuff and gave me some things to think about. 

I'm thinking releasing this a major would be fine if Material-ui already pulled the trigger on V1.  One thought I have is what if they squeeze in another big breaking change before the V1 version comes out on May 17th. Then I'm in that same position again.  I'm thinking of maybe just doing a patch here to help some people who are stuck with this issue.  Then on the 17th when V1 finally comes out doing a major release to sync with that.

**Comment by baer** [comment]
If you do a patch, this will break anybody who has `^` in their package.json the next time they run `npm install` on a fresh repo OR if they run `npm update` on a current one.

**Comment by baer** [comment]
You could do a 2.x.x-beta-1 as a pre-release. That wouldn't break existing users but would tide folks over who need this until next week. Also, I didn't know it was going live next week. That's super exciting.

**Comment by gregnb** [comment]
@baer Ok, thanks for pointing this out. With that said I'm going to go ahead with releasing another major and keep my fingers crossed Material-ui doesn't change too much before the 17th.  Appreciate your help!

**Comment by baer** [comment]
For sure. Either approach is fine and TBH now that I know it's only a week away I'd be fine to just wait it out. FWIW, I've been using the 1.x line since beta 20something and this is the only major I've seen.I'm crossing my fingers for ya.

**Comment by gregnb** [comment]
Yeah it's been pretty smooth sailing.  At work we're on about the same version

```
    "material-ui": "^1.0.0-beta.26",
    "material-ui-icons": "^1.0.0-beta.5",
```

and just waiting until next week to get it over with :)

**Pull request merged**
