### PR TITLE
Replace gridList to grid

### PR DESCRIPTION
**Pull request by wdh2100**
#1559

The usability is the same.
However, there may be some differences.

It looks like the use of abnormal components(`GridList`), so I fixed it.

And there are also component changes in v5.

GridList => ImageList

These changes seem to clarify the purpose.

https://material-ui.com/components/grid/
https://material-ui.com/components/grid-list/

### CODE REVIEW

**Comment by gregnb** [comment]
@wdh2100 whats your email or npm user? so i can add you for contributors

**Comment by wdh2100** [comment]
@gregnb 
thanks 
my username is dohwoo

**Comment by patorjk** [comment]
@wdh2100 are you up for doing the next release?

**Comment by wdh2100** [comment]
@patorjk 

Not yet...
What changes should be included next release?

**Comment by gregnb** [comment]
@wdh2100 dohwoo is not valid username on npm

**Comment by wdh2100** [comment]
@gregnb 

hmm... 

Could you do it again with this?
Email : wdh2100@gmail.com

**Comment by gregnb** [comment]
@wdh2100 has to be a username

**Comment by wdh2100** [comment]
image

Isn't this your username?

**Comment by wdh2100** [comment]
@gregnb 

oh sorry

Add my github account

image

**Comment by gregnb** [comment]
@wdh2100 all set

**Comment by patorjk** [comment]
> @patorjk
> 
> Not yet...
> What changes should be included next release?

I would just include your 3 PRs and update the package version to 3.7.0.

**Comment by wdh2100** [comment]
@patorjk 

Okay.
I will test some more and publish the version (3.7.0).

**Pull request merged**
