### PR TITLE
Added support for Shift + Click selection of rows

### PR DESCRIPTION
**Pull request by patorjk**
An implementation of the feature suggested in https://github.com/gregnb/mui-datatables/issues/663

The UX for shift+click is modeled off of how GMail does it. For example, if you select/unselect row A and then hold shift and select/unselect row B:

- If row B is being selected, then the rows between A and B (including A) will be selected.
- If row B is being unselected, then the rows between A and B (including A) will be unselected. 

If any filters are removed or columns resorted or selection headers toggled or data fetched (in the case of Server Side tables), between the selection of rows A and B, then there will be no special effect.

### CODE REVIEW

**Comment by patorjk** [comment]
This PR is most likely not compatible with https://github.com/gregnb/mui-datatables/pull/825, however, I could adjust it so that in the MUIDataTable.js file, when it was in the process of adding the adjacent rows, it would stop if it hit the maxSelectedRows threshold.

**Comment by gabrielliwerant** [comment]
This is a cool feature, thank you for working on this!

I just reviewed and suggested a number of changes to https://github.com/gregnb/mui-datatables/pull/825, so how about we wait for that to be merged and integrated with yours before review?

**Comment by patorjk** [comment]
Sounds good, I’ll be unavailable next week but could make any adjustments tomorrow or the week after that.

**Comment by gabrielliwerant** [comment]
@patorjk The `isRowSelectable` changes are in latest master now, if you want to pull those.

**Comment by patorjk** [comment]
Sounds good, I’ll pull them and update this PR early next week!

**Pull request merged**
