### PR TITLE
Issue 1604: isRowSelectable should be PropTypes.bool

### PR DESCRIPTION
**Pull request by lounsbrough**
It seems that this would resolve issue https://github.com/gregnb/mui-datatables/issues/1604

### CODE REVIEW

**Comment by lounsbrough** [comment]
Runs fine locally, tests seem to maybe be in a bad state, I get exceptions when running. Looking at the tests I don't see anything I would expect to have broken with this change.

**Comment by wdh2100** [comment]
@lounsbrough 

TableSelectCell is an internal component, so boolean is correct.

However, it may be confusing because it looks different from the document.
What do you think?

**Comment by lounsbrough** [comment]
I think either way is likely ok, but boolean internally may be simpler.

**Review by wdh2100 — APPROVED** [review]
LGTM 👍

**Comment by jeanatpi** [comment]
Maybe I'm wrong but this bug is still present in last release 3.7.6.

Is there any workaround?

**Pull request merged**
