### PR TITLE
Fix for Issue 483

### PR DESCRIPTION
**Pull request by gabrielliwerant**
Fixes issue https://github.com/gregnb/mui-datatables/issues/483 (`changedColumn` was showing filtered value instead of column name).

When removing filters (`TableFilterList.js`), there is no information about column names, so `null` is supplied instead. We could default to the filter value removed in this case (as it was previously), but not sure what is best.

UPDATE:

The proper column name should now always be passed along with the filter information. This was done by passing the column names along to the filter list component, and correlating them with filter position (which matches column position).

### CODE REVIEW

**Comment by gregnb** [comment]
Alright let me think on this one maybe we can come up with a better solution to solve that null issue

**Comment by gabrielliwerant** [comment]
I added a state value to pass into the `TableFilterList` in order to prevent the `null` after removing filters. Also added testing around the filtered column name in the callback in order to help prevent regressions. @gregnb

**Comment by gabrielliwerant** [comment]
@gregnb Added a more elegant fix here which should solve the outstanding issues.

**Comment by gregnb** [comment]
Looks great thanks @gabrielliwerant

**Pull request merged**
